name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-docker-image:
    name: Create and publish Docker image
    if: (github.ref == 'refs/heads/master')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,priority=1
            type=raw,value=develop,priority=2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}